apiVersion: v2
name: structurizr
description: The Structurizr Helm chart deploys Structurizr On premise flavor. Structurizr is a web-based rendering tool designed to help software development teams create software architecture diagrams and documentation.

type: application
icon: "https://avatars.githubusercontent.com/u/7525795?s=200&v=4"
keywords:
  - structurizr
  - diagrams
  - kubernetes
sources:
  - https://structurizr.com/help/on-premises

version: 0.5.0
appVersion: "2025.11.09"
